uint16 OK                              = 0
uint16 ERR_LIDAR_DEVICE_NOT_FOUND      = 20021
uint16 ERR_LIDAR_OPEN_FAILED           = 20022
uint16 ERR_LIDAR_SCAN_START_FAILED     = 20023
uint16 ERR_LIDAR_FRAME_DROP            = 20024
uint16 ERR_LIDAR_OVERHEATING           = 20025
uint16 ERR_LIDAR_LIVOX_SDK_ERROR       = 20026
uint16 ERR_LIDAR_ETH_DISCONNECTED      = 20027

uint16 error_code
string message
