<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>perception</name>
  <version>0.1.0</version>
  <description>perception implementation</description>
  <maintainer email="dev@striding.ai">Striding Dev</maintainer>
  <license>Apache-2.0</license>
  <depend>perception_msgs</depend>
  <depend>perception_msgs</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
