# SetStreamParameters Service - Dynamically adjust stream parameters

float32 output_frequency    # Output frequency (Hz), 0=don't change
float32 max_velocity        # Max joint velocity (rad/s), 0=don't change
float32 max_acceleration    # Max joint acceleration (rad/s²), 0=don't change
float32 max_jerk            # Max jerk (rad/s³), 0=don't change
---
# Response
bool success
uint16 error_code
string message
